defaults: &defaults
  working_directory: /go/src/github.com/storageos/go-cli
  docker:
    - image: circleci/golang:1.10.3

version: 2
jobs:
  test:
    <<: *defaults
    steps:
      - checkout
      - run: mkdir -p output
      - run: go vet ./... | tee output/go-vet.out
      - run: go get github.com/jstemmer/go-junit-report
      - run:
          name: Run unit tests
          command: |
            trap "go-junit-report <output/go-test.out > output/go-test-report.xml" EXIT
            go test -v -race ./... | tee output/go-test.out
      - store_test_results:
          path: output
  build:
    <<: *defaults
    steps:
      - checkout
      - run: go get github.com/mitchellh/gox
      - run: make release
      - store_artifacts:
          path: /go/src/github.com/storageos/go-cli/cmd/storageos/release/
          destination: binaries
      - persist_to_workspace:
          root: cmd/storageos
          paths:
            - release
  preprod_release:
    <<: *defaults
    steps:
      - checkout
      - attach_workspace:
          at:  cmd/storageos
      - setup_remote_docker
      - run: |
          TAG=$CIRCLE_SHA1
          REPO=${STAGING_REPO}
          docker build -t ${REPO}:$TAG .
          docker login -u $DOCKER_USER -p $(echo $DOCKER_PASS | base64 --decode)
          docker push $REPO:$TAG
  prod_release:
    <<: *defaults
    steps:
      - checkout
      - attach_workspace:
          at:  cmd/storageos
      - run: go get github.com/tcnksm/ghr
      - run: ghr -t $GITHUB_TOKEN -u $CIRCLE_PROJECT_USERNAME -r $CIRCLE_PROJECT_REPONAME --replace `git describe --tags` cmd/storageos/release/
      - setup_remote_docker
      - run: |
          TAG=$CIRCLE_TAG
          REPO=storageos/cli
          docker build -t ${REPO}:$TAG .
          docker login -u $DOCKER_USER -p $(echo $DOCKER_PASS | base64 --decode)
          docker push $REPO:$TAG
workflows:
  version: 2
  push:
    jobs:
      - test:
          filters:
            tags:
              only: /.*/
      - build:
          requires:
            - test
          filters:
            tags:
              only: /.*/
      - preprod_release:
          requires:
            - test
            - build
          filters:
            branches:
              only: master
      - prod_release:
          requires:
            - test
            - build
          filters:
            tags:
              only: /[0-9]+(\.[0-9]+).*/
            branches:
              ignore: /.*/
