/*
 * StorageOS API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 2.0.0
 * Contact: info@storageos.com
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi
// FsType The file system type of a volume. \"block\" is a raw block device (no filesystem). 
type FsType string

// List of FsType
const (
	EXT2 FsType = "ext2"
	EXT3 FsType = "ext3"
	EXT4 FsType = "ext4"
	XFS FsType = "xfs"
	BTRFS FsType = "btrfs"
	BLOCK FsType = "block"
)
