/*
 * StorageOS API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 2.3.0-alpha
 * Contact: info@storageos.com
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

// ReplicaDeploymentInfoAllOf struct for ReplicaDeploymentInfoAllOf
type ReplicaDeploymentInfoAllOf struct {
	Health       ReplicaHealth `json:"health,omitempty"`
	SyncProgress SyncProgress  `json:"syncProgress,omitempty"`
}
