// Code generated by "stringer -type=FSType fs_types.go"; DO NOT EDIT.

package mount

import "strconv"

const _FSType_name = "ext2ext3ext4xfsbtrfs"

var _FSType_index = [...]uint8{0, 4, 8, 12, 15, 20}

func (i FSType) String() string {
	if i < 0 || i >= FSType(len(_FSType_index)-1) {
		return "FSType(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _FSType_name[_FSType_index[i]:_FSType_index[i+1]]
}
