// Code generated by template-doc-gen.
// DO NOT EDIT!

package constants

// ClusterHealthContextTemplate is the Go template for type ClusterHealthContext
var ClusterHealthContextTemplate = `
Fields:
  {{.Address}}
  {{.CPStatus}}
  {{.DPStatus}}
  {{.DirectFSClient}}
  {{.Director}}
  {{.FS}}
  {{.FSDriver}}
  {{.KV}}
  {{.KVWrite}}
  {{.NATS}}
  {{.Node}}
  {{.Status}}
`

// ConnectivityContextTemplate is the Go template for type ConnectivityContext
var ConnectivityContextTemplate = `
Fields:
  {{.Address}}
  {{.Error}}
  {{.Latency}}
  {{.Name}}
  {{.Source}}
  {{.Status}}
  {{.Test}}
`

// LoggerContextTemplate is the Go template for type LoggerContext
var LoggerContextTemplate = `
Fields:
  {{.Categories}}
  {{.Filter}}
  {{.Level}}
  {{.Node}}
`

// LogStreamContextTemplate is the Go template for type LogStreamContext
var LogStreamContextTemplate = `
Fields:
  {{.Action}}
  {{.Category}}
  {{.Error}}
  {{.Host}}
  {{.Level}}
  {{.Module}}
  {{.Msg}}
  {{.Text}}
  {{.Time}}
`

// NamespaceContextTemplate is the Go template for type NamespaceContext
var NamespaceContextTemplate = `
Fields:
  {{.Description}}
  {{.DisplayName}}
  {{.Label <string>}}
  {{.Labels}}
  {{.Name}}
`

// NodeContextTemplate is the Go template for type NodeContext
var NodeContextTemplate = `
Fields:
  {{.Address}}
  {{.Capacity}}
  {{.CapacityUsed}}
  {{.FailureDomain}}
  {{.Health}}
  {{.Label <string>}}
  {{.Labels}}
  {{.Name}}
  {{.Region}}
  {{.Scheduler}}
  {{.Version}}
  {{.Volumes}}
`

// NodeHealthContextTemplate is the Go template for type NodeHealthContext
var NodeHealthContextTemplate = `
Fields:
  {{.ChangedAt}}
  {{.Message}}
  {{.Name}}
  {{.Status}}
  {{.T}}
  {{.Type}}
  {{.UpdatedAt}}
`

// PolicyContextTemplate is the Go template for type PolicyContext
var PolicyContextTemplate = `
Fields:
  {{.APIGroup}}
  {{.Group}}
  {{.ID}}
  {{.Namespace}}
  {{.NonResourcePath}}
  {{.Readonly}}
  {{.Resource}}
  {{.User}}
`

// PoolContextTemplate is the Go template for type PoolContext
var PoolContextTemplate = `
Fields:
  {{.CapacityUsed}}
  {{.Default}}
  {{.DeviceSelector}}
  {{.Label <string>}}
  {{.Labels}}
  {{.Name}}
  {{.NodeSelector}}
  {{.Nodes}}
  {{.Total}}
`

// RuleContextTemplate is the Go template for type RuleContext
var RuleContextTemplate = `
Fields:
  {{.Active}}
  {{.Label <string>}}
  {{.Labels}}
  {{.Name}}
  {{.RuleAction}}
  {{.Selector}}
`

// UserContextTemplate is the Go template for type UserContext
var UserContextTemplate = `
Fields:
  {{.Groups}}
  {{.Role}}
  {{.UUID}}
  {{.Username}}
`

// VolumeContextTemplate is the Go template for type VolumeContext
var VolumeContextTemplate = `
Fields:
  {{.Label <string>}}
  {{.Labels}}
  {{.Location}}
  {{.MountedBy}}
  {{.Name}}
  {{.NodeSelector}}
  {{.Replicas}}
  {{.Size}}
  {{.Status}}
`
// ClusterTemplate is the Go template for type Cluster
var ClusterTemplate = `
Fields:
  {{.ID}}
  {{.Size}}
  {{.Name}}
  {{.AccountID}}
  {{index .Nodes <index>}}
    {{.ID}}
    {{.Name}}
    {{.AdvertiseAddress}}
    {{.CreatedAt}}
    {{.UpdatedAt}}
    {{.Health}}
      {{.CP}}
        {{.KV}}
          {{.Status}}
          {{.UpdatedAt}}
          {{.ChangedAt}}
          {{.Message}}
        {{.KVWrite}}
          {{.Status}}
          {{.UpdatedAt}}
          {{.ChangedAt}}
          {{.Message}}
        {{.NATS}}
          {{.Status}}
          {{.UpdatedAt}}
          {{.ChangedAt}}
          {{.Message}}
        {{.Scheduler}}
          {{.Status}}
          {{.UpdatedAt}}
          {{.ChangedAt}}
          {{.Message}}
      {{.DP}}
        {{.DirectFSClient}}
          {{.Status}}
          {{.UpdatedAt}}
          {{.ChangedAt}}
          {{.Message}}
        {{.DirectFSServer}}
          {{.Status}}
          {{.UpdatedAt}}
          {{.ChangedAt}}
          {{.Message}}
        {{.Director}}
          {{.Status}}
          {{.UpdatedAt}}
          {{.ChangedAt}}
          {{.Message}}
        {{.FSDriver}}
          {{.Status}}
          {{.UpdatedAt}}
          {{.ChangedAt}}
          {{.Message}}
        {{.FS}}
          {{.Status}}
          {{.UpdatedAt}}
          {{.ChangedAt}}
          {{.Message}}
  {{.CreatedAt}}
  {{.UpdatedAt}}
`

// ConnectivityResultTemplate is the Go template for type ConnectivityResult
var ConnectivityResultTemplate = `
Fields:
  {{.Label}}
  {{.Address}}
  {{.Source}}
  {{.LatencyNS}}
  {{.Error}}
`

// LicenceTemplate is the Go template for type Licence
var LicenceTemplate = `
Fields:
  {{.ArrayUUID}}
  {{.ClusterID}}
  {{.CustomerID}}
  {{.CustomerName}}
  {{.Storage}}
  {{.ValidUntil}}
  {{.LicenceType}}
  {{index .Features <key>}}
  {{.Unregistered}}
`

// NamespaceTemplate is the Go template for type Namespace
var NamespaceTemplate = `
Fields:
  {{.ID}}
  {{.Name}}
  {{.DisplayName}}
  {{.Description}}
  {{index .Labels <key>}}
  {{.CreatedAt}}
  {{.CreatedBy}}
  {{.UpdatedAt}}
`

// NodeTemplate is the Go template for type Node
var NodeTemplate = `
Fields:
  {{.HostID}}
  {{.Name}}
  {{.Description}}
  {{.CreatedAt}}
  {{.UpdatedAt}}
  {{.Health}}
  {{.HealthUpdatedAt}}
  {{index .VersionInfo <key>}}
  {{.Version}}
  {{.Revision}}
  {{.Scheduler}}
  {{.Cordon}}
  {{.Drain}}
  {{.VolumeStats}}
    {{.MasterVolumeCount}}
    {{.ReplicaVolumeCount}}
    {{.VirtualVolumeCount}}
  {{.CapacityStats}}
    {{.TotalCapacityBytes}}
    {{.AvailableCapacityBytes}}
    {{.ProvisionedCapacityBytes}}
`

// PolicyTemplate is the Go template for type Policy
var PolicyTemplate = `
Fields:
  {{.Spec}}
    {{.User}}
    {{.Group}}
    {{.Readonly}}
    {{.APIGroup}}
    {{.Resource}}
    {{.Namespace}}
    {{.NonResourcePath}}
`

// PoolTemplate is the Go template for type Pool
var PoolTemplate = `
Fields:
  {{.ID}}
  {{.Name}}
  {{.Description}}
  {{.Default}}
  {{.NodeSelector}}
  {{.DeviceSelector}}
  {{.CapacityStats}}
    {{.TotalCapacityBytes}}
    {{.AvailableCapacityBytes}}
    {{.ProvisionedCapacityBytes}}
  {{index .Nodes <index>}}
    {{.HostID}}
    {{.Name}}
    {{.Description}}
    {{.CreatedAt}}
    {{.UpdatedAt}}
    {{.Health}}
    {{.HealthUpdatedAt}}
    {{index .VersionInfo <key>}}
    {{.Version}}
    {{.Revision}}
    {{.Scheduler}}
    {{.Cordon}}
    {{.Drain}}
    {{.VolumeStats}}
      {{.MasterVolumeCount}}
      {{.ReplicaVolumeCount}}
      {{.VirtualVolumeCount}}
    {{.CapacityStats}}
      {{.TotalCapacityBytes}}
      {{.AvailableCapacityBytes}}
      {{.ProvisionedCapacityBytes}}
  {{index .Labels <key>}}
`

// RuleTemplate is the Go template for type Rule
var RuleTemplate = `
Fields:
  {{.ID}}
  {{.Name}}
  {{.Namespace}}
  {{.Description}}
  {{.Active}}
  {{.Weight}}
  {{.RuleAction}}
  {{.Selector}}
  {{index .Labels <key>}}
`

// UserTemplate is the Go template for type User
var UserTemplate = `
Fields:
  {{.UUID}}
  {{.Username}}
  {{index .Groups <index>}}
  {{.Password}}
  {{.Role}}
`

// VolumeTemplate is the Go template for type Volume
var VolumeTemplate = `
Fields:
  {{.ID}}
  {{.Inode}}
  {{.Name}}
  {{.Size}}
  {{.Pool}}
  {{.FSType}}
  {{.Description}}
  {{index .Labels <key>}}
  {{.Namespace}}
  {{.NodeSelector}}
  {{.Master}}
    {{.ID}}
    {{.Inode}}
    {{.Node}}
    {{.NodeName}}
    {{.Health}}
    {{.Status}}
    {{.CreatedAt}}
  {{.Mounted}}
  {{.MountDevice}}
  {{.Mountpoint}}
  {{.MountedAt}}
  {{.MountedBy}}
  {{index .Replicas <index>}}
    {{.ID}}
    {{.Inode}}
    {{.Node}}
    {{.NodeName}}
    {{.Health}}
    {{.Status}}
    {{.CreatedAt}}
  {{.Health}}
  {{.Status}}
  {{.StatusMessage}}
  {{.MkfsDone}}
  {{.MkfsDoneAt}}
  {{.CreatedAt}}
  {{.CreatedBy}}
`

// VersionResponseTemplate is the Go template for type VersionResponse
var VersionResponseTemplate = `
Fields:
  {{.Client}}
    {{.Name}}
    {{.BuildDate}}
    {{.Revision}}
    {{.Version}}
    {{.APIVersion}}
    {{.GoVersion}}
    {{.OS}}
    {{.Arch}}
    {{.KernelVersion}}
    {{.Experimental}}
  {{.Server}}
    {{.Name}}
    {{.BuildDate}}
    {{.Revision}}
    {{.Version}}
    {{.APIVersion}}
    {{.GoVersion}}
    {{.OS}}
    {{.Arch}}
    {{.KernelVersion}}
    {{.Experimental}}
`
